import fs from 'node:fs';
import { memoryIssues } from '../memory/index.mjs';
import { readWorkUnit, workUnitPath, workUnitPlanDigest, workUnitPlanProjection, checkWorkUnit, parseWorkUnitResults, workUnitVerificationBinding, recordWorkUnitVerification, replayWorkUnitVerification, changedWorkUnitBehaviorPaths } from '../work-units/index.mjs';
import os from 'node:os';
import path from 'node:path';
import { applicableRiskSignals, checkProject, evaluateCompletionTaskRoute, evaluateTaskApproval, readBoundedTaskFile, readCanonicalPath, trustedProfessionalTaskContext, validateConfig, validateReviewMode, validateTaskLevel } from '../governance/index.mjs';
import { runGit, runNpmScript } from '../../adapters/process/index.mjs';
import { assertNoLinkAncestor, readJson, sameSnapshot, snapshotPath } from '../../adapters/filesystem/index.mjs';
import { CONFIG_PATH, PACKAGE_ROOT, TOOL_VERSION } from '../../constants.mjs';
import { clientGovernanceMatchers } from '../../catalogs/index.mjs';
import { isProductionScopePath, scanProject, SURFACE_EVIDENCE_MARKER_PREFIX, verificationNpmCommands } from '../repository/index.mjs';
import { writeAtomicFile } from '../../adapters/filesystem/index.mjs';
import { usageError } from '../../kernel/index.mjs';
import { isSafeRelative, normalizeRelative, sha256, stableJson } from '../../shared/index.mjs';
import { evaluateProductionReadiness } from './production-readiness.mjs';
import { evaluateSurfaceVerification } from './surface-verification.mjs';
import { assessHarvestEligibility, capabilitySourceChanged, completionCapabilityHarvestSummary, isProductionCapabilityPath } from '../capabilities/index.mjs';

export const PRE_COMMIT_HOOK_MARKER = 'ai-code-governance:pre-commit-v1';

function git(root, args) {
  const result = runGit(root, args, { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
  if (result.error || result.status !== 0) {
    throw usageError(`Git command failed while preparing the completion gate: git ${args.join(' ')}.`);
  }
  return result.stdout.trim();
}

function resolveGitRepository(target) {
  const root = path.resolve(target);
  const gitRoot = git(root, ['rev-parse', '--show-toplevel']);
  return path.resolve(gitRoot);
}

// The project flow writes its human-readable plan digest into the flow ledger. Binding it
// into the task approval makes a plan change invalidate a prior approval, exactly like a
// change digest does. Absent or malformed flow state simply binds nothing.
function readFlowPlanDigest(root) {
  try {
    const relative = readCanonicalPath(root, 'docs/ai/flow-state.json');
    const state = readJson(path.join(root, relative));
    const digest = state ? state.plan && state.plan.digest : null;
    return typeof digest === 'string' && /^[a-f0-9]{64}$/.test(digest) ? digest : null;
  } catch {
    return null;
  }
}

function hookPathFor(root) {
  const hooks = git(root, ['rev-parse', '--git-path', 'hooks']);
  return path.resolve(root, hooks, 'pre-commit');
}

function shellQuote(value) {
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

function hookContent() {
  const node = shellQuote(process.execPath);
  const entrypoint = shellQuote(path.join(PACKAGE_ROOT, 'bin', 'aicg.js'));
  return `#!/bin/sh\n# ${PRE_COMMIT_HOOK_MARKER}\n# Generated by AI Code Governance. Reinstall with aicg hook install after relocating the CLI.\nset -eu\nrepo_root=$(git rev-parse --show-toplevel)\nexec ${node} ${entrypoint} complete "$repo_root" --from-git-hook\n`;
}

function hookState(hookPath) {
  const snapshot = snapshotPath(hookPath);
  if (snapshot.kind === 'missing') return { status: 'not-installed', snapshot };
  if (snapshot.kind !== 'file') return { status: 'conflict', snapshot };
  const content = fs.readFileSync(hookPath, 'utf8');
  return content.includes(PRE_COMMIT_HOOK_MARKER)
    ? { status: 'managed', snapshot }
    : { status: 'conflict', snapshot };
}

function digest(value) {
  return sha256(stableJson(value));
}

export function inspectCommitHook(target) {
  const root = resolveGitRepository(target);
  const hookPath = hookPathFor(root);
  const state = hookState(hookPath);
  return { targetRoot: root, hookPath, hookStatus: state.status, before: state.snapshot };
}

export function prepareCommitHookInstall(target) {
  const inspected = inspectCommitHook(target);
  const { targetRoot: root, hookPath, hookStatus, before } = inspected;
  if (hookStatus === 'conflict') {
    throw usageError(`Refuse to replace the existing pre-commit hook at ${hookPath}. Preserve it or integrate aicg manually.`);
  }
  const base = {
    schemaVersion: 1,
    intent: 'governance.install-precommit',
    targetRoot: root,
    hookPath,
    before,
    hookStatus,
    contentSha256: sha256(hookContent()),
    toolVersion: TOOL_VERSION,
    requiredPermissions: ['write-git-hook'],
    verification: 'git-pre-commit-staged-governance-check',
    boundaries: [
      'The generated hook validates the Git index snapshot at commit time; it does not run on ordinary conversation turns.',
      'The hook never writes project files, stages files, or synthesizes business memory or Skills.',
      'Project behavior commands remain explicit manual aicg complete --verify invocations until separately configured and evidenced.',
    ],
  };
  return { ...base, planHash: digest(base) };
}

export function assertCommitHookPlanFresh(plan) {
  if (!plan || plan.schemaVersion !== 1 || plan.intent !== 'governance.install-precommit' || typeof plan.targetRoot !== 'string' || typeof plan.hookPath !== 'string') {
    throw usageError('Commit-hook installation plan is invalid. Generate a new plan.');
  }
  const root = resolveGitRepository(plan.targetRoot);
  if (root !== plan.targetRoot || hookPathFor(root) !== plan.hookPath) throw usageError('Commit-hook installation plan targets a different Git repository. Generate a new plan.');
  const state = hookState(plan.hookPath);
  if (state.status === 'conflict' || !sameSnapshot(state.snapshot, plan.before)) {
    throw usageError('Commit-hook installation plan is stale because the existing hook changed. Generate a new plan.');
  }
  const { planHash, ...base } = plan;
  if (planHash !== digest(base) || plan.contentSha256 !== sha256(hookContent())) {
    throw usageError('Commit-hook installation plan is invalid or was created by a different CLI build. Generate a new plan.');
  }
  return true;
}

export function installCommitHook(plan) {
  assertCommitHookPlanFresh(plan);
  writeAtomicFile(plan.hookPath, hookContent(), 0o755);
  return { hookPath: plan.hookPath, status: 'installed', marker: PRE_COMMIT_HOOK_MARKER };
}

function stagedPaths(root) {
  const result = runGit(root, ['diff', '--cached', '--name-only', '-z', '--no-renames'], { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
  if (result.error || result.status !== 0) throw usageError('Cannot read the Git index for the pre-commit completion gate.');
  return result.stdout.split('\0').filter(Boolean).sort((left, right) => left.localeCompare(right));
}

function changedPaths(root) {
  const paths = [];
  // Disable rename collapsing so moving a sensitive source into docs cannot hide its removal.
  // A gitlink is a member-repository boundary, not a parent directory change: the parent
  // neither owns nor governs member content, so a moved or dirty submodule must not be
  // rejected as an unapprovable directory path here.
  for (const args of [
    ['diff', '--cached', '--name-only', '-z', '--no-renames', '--ignore-submodules=all', 'HEAD'],
    ['diff', '--name-only', '-z', '--no-renames', '--ignore-submodules=all'],
    ['ls-files', '--others', '--exclude-standard', '-z'],
  ]) {
    const result = runGit(root, args, { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
    if (result.error || result.status !== 0) throw usageError('Cannot read changed paths for the completion gate.');
    paths.push(...result.stdout.split('\0').filter(Boolean));
  }
  return [...new Set(paths)].sort((left, right) => left.localeCompare(right));
}

function completionTaskRoute(scan, paths, taskLevel, gitRoot = scan.root) {
  let config;
  try {
    assertNoLinkAncestor(scan.root, CONFIG_PATH);
    config = validateConfig(readJson(path.join(scan.root, CONFIG_PATH)));
  } catch (error) {
    throw usageError(`Cannot read task routing configuration for the completion gate: ${error.message}`);
  }
  const behaviorPaths = changedWorkUnitBehaviorPaths(scan.root, { ...scan, memoryGitRoot: gitRoot }, paths);
  const productionPaths = paths.filter(isProductionScopePath);
  const trustedBehaviorChange = productionPaths.length > 0 && behaviorPaths.length === 0 ? false : null;
  return { config, behaviorPaths, trustedBehaviorChange, taskRoute: evaluateCompletionTaskRoute(paths, config, taskLevel, { trustedBehaviorChange }) };
}

function completionChangeDigest(gitRoot, snapshotRoot, paths, mode, approvalEvidence, workUnitRelative = null) {
  if (paths.length > 10000) throw usageError('Cannot bind more than 10000 changed paths.');
  const approvalPath = typeof approvalEvidence === 'string' && isSafeRelative(approvalEvidence) ? normalizeRelative(approvalEvidence) : null;
  const records = (args) => {
    const map = new Map();
    for (const record of git(gitRoot, args).split('\0').filter(Boolean)) {
      const separator = record.indexOf('\t');
      if (separator < 0) throw usageError('Cannot read bounded change identity.');
      const relative = record.slice(separator + 1);
      if (map.has(relative)) throw usageError('Cannot approve an unresolved index.');
      map.set(relative, record.slice(0, separator));
    }
    return map;
  };
  const head = records(['ls-tree', '-r', '-z', 'HEAD']);
  const index = records(['ls-files', '--stage', '-z']);
  let totalBytes = 0;
  const contentHash = (bytes, relative) => {
    totalBytes += bytes.length;
    if (totalBytes > 32 * 1024 * 1024) throw usageError('Changed content exceeds the 32 MiB approval budget.');
    if (relative === workUnitRelative) return sha256(stableJson(workUnitPlanProjection(JSON.parse(bytes.toString('utf8')))));
    if (relative !== approvalPath) return sha256(bytes);
    // The receipt cannot hash its own planHash. Every other field is bound;
    // malformed receipts are still rejected by the independent evidence parser.
    try {
      const value = JSON.parse(bytes.toString('utf8'));
      if (value && typeof value === 'object' && !Array.isArray(value)) {
        delete value.planHash;
        return sha256(stableJson(value));
      }
    } catch { /* Preserve malformed bytes for fail-closed evidence validation. */ }
    return sha256(bytes);
  };
  const snapshot = (relative) => {
    assertNoLinkAncestor(snapshotRoot, relative, { allowFinalLink: true });
    const absolute = path.join(snapshotRoot, relative);
    let stat;
    try { stat = fs.lstatSync(absolute); } catch (error) { if (error.code === 'ENOENT') return { kind: 'missing' }; throw error; }
    if (stat.isSymbolicLink()) return { kind: 'link', sha256: sha256(fs.readlinkSync(absolute)) };
    if (!stat.isFile()) throw usageError('Approval changed paths must be files or links, not directories or devices.');
    return { kind: 'file', executable: (stat.mode & 0o111) !== 0, sha256: contentHash(readBoundedTaskFile(snapshotRoot, relative, 2 * 1024 * 1024), relative) };
  };
  const changes = [...new Set(paths)].sort().map((relative) => {
    if (typeof relative !== 'string' || relative.length > 4096 || !isSafeRelative(relative)) throw usageError('Cannot bind unsafe changed paths.');
    let staged = index.get(relative) ?? null;
    if (staged && !/^\d{6} [a-f0-9]{40,64} 0$/.test(staged)) throw usageError('Cannot approve an unresolved index.');
    if ((relative === approvalPath || relative === workUnitRelative) && staged) {
      const blob = runGit(gitRoot, ['show', `:${relative}`], { encoding: null, timeout: 15000, maxBuffer: 256 * 1024 });
      if (blob.error || blob.status !== 0) throw usageError('Cannot read staged approval evidence.');
      staged = `${staged.slice(0, 6)} ${contentHash(blob.stdout, relative)}`;
    }
    return { path: relative, before: head.get(relative) ?? null, staged, ...(mode === 'manual' ? { worktree: snapshot(relative) } : {}) };
  });
  return digest({ schemaVersion: 1, mode, head: git(gitRoot, ['rev-parse', '--verify', 'HEAD^{commit}']), changes });
}

function capabilityChangedPaths(scan, paths) {
  const sources = new Map(scan.files.filter((file) => file.type === 'file' && file.contentScannable !== false).map((file) => [file.relative, file]));
  const changed = [];
  const unavailable = { paths: [], reason: 'product-change-evidence-unavailable' };
  for (const relative of paths) {
    if (!isProductionCapabilityPath(relative) || !sources.has(relative)) continue;
    const before = runGit(scan.root, ['show', `HEAD:${relative}`], { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
    if (before.error) return unavailable;
    if (before.status !== 0) {
      // Distinguish an added source from an unreadable tracked blob.
      const entry = runGit(scan.root, ['ls-tree', '-z', 'HEAD', '--', relative], { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
      if (entry.error || entry.status !== 0 || entry.stdout.length > 0) return unavailable;
    }
    try {
      assertNoLinkAncestor(scan.root, relative);
      const after = fs.readFileSync(sources.get(relative).absolute, 'utf8');
      if (before.status !== 0 || capabilitySourceChanged(before.stdout, after)) changed.push(relative);
    } catch {
      return unavailable;
    }
  }
  return { paths: changed };
}

function verificationInputSnapshot(scan, knownPaths = [], evidencePaths = []) {
  const unavailable = { reason: 'product-change-evidence-unavailable' };
  if (scan.scanBudget?.complete !== true) return unavailable;
  const relevant = (relative) => evidencePaths.includes(relative) || isProductionCapabilityPath(relative) || relative === 'package.json' || relative.endsWith('/package.json');
  try {
    const index = git(scan.root, ['ls-files', '--stage', '-z']).split('\0').filter(Boolean).map((entry) => {
      const separator = entry.indexOf('\t');
      if (separator < 0) throw new Error('Invalid index record.');
      return { path: entry.slice(separator + 1), entry: entry.slice(0, separator) };
    }).filter((entry) => relevant(entry.path));
    const paths = [...new Set([...knownPaths, ...scan.files.map((file) => file.relative), ...index.map((entry) => entry.path)])]
      .filter(relevant).sort((left, right) => left.localeCompare(right));
    const sources = paths.map((relative) => {
      assertNoLinkAncestor(scan.root, relative, { allowFinalLink: true });
      return { path: relative, snapshot: snapshotPath(path.join(scan.root, relative)) };
    });
    const fields = git(scan.root, ['diff', '--name-status', '-z', '--no-renames', 'HEAD']).split('\0').filter(Boolean);
    if (fields.length % 2 !== 0) return unavailable;
    const diff = [];
    for (let index = 0; index < fields.length; index += 2) {
      if (relevant(fields[index + 1])) diff.push({ status: fields[index], path: fields[index + 1] });
    }
    return { paths, fingerprint: digest({ head: git(scan.root, ['rev-parse', 'HEAD']), sources, index, diff }) };
  } catch {
    return unavailable;
  }
}

function withIndexSnapshot(root, action) {
  const snapshot = fs.mkdtempSync(path.join(os.tmpdir(), 'aicg-index-snapshot-'));
  try {
    // Git parses backslashes in pathspecs as escapes, so the prefix must use forward slashes on
    // every platform; a Windows path here left the snapshot empty.
    const prefix = `${snapshot.replace(/\\/g, '/')}/`;
    const result = runGit(root, ['checkout-index', '--all', `--prefix=${prefix}`], { timeout: 30000, maxBuffer: 4 * 1024 * 1024 });
    if (result.error || result.status !== 0) throw usageError('Cannot materialize the Git index for the pre-commit completion gate.');
    return action(snapshot);
  } finally {
    fs.rmSync(snapshot, { recursive: true, force: true });
  }
}

const NPM_SHORTHANDS = new Map([
  ['npm test', 'test'],
]);

function safeNpmVerifications(scan) {
  return verificationNpmCommands(scan.commands)
    .sort((left, right) => left.command.localeCompare(right.command));
}

function discoveredVerification(scan, requestedCommand) {
  const allowed = safeNpmVerifications(scan);
  const shorthandName = NPM_SHORTHANDS.get(requestedCommand);
  const canonicalCommand = shorthandName ? `npm run ${shorthandName}` : requestedCommand;
  const selected = allowed.find((candidate) => candidate.command === canonicalCommand);
  if (!selected) {
    const choices = allowed.length > 0 ? allowed.map((candidate) => candidate.command).join(', ') : '(none discovered)';
    throw usageError(`Completion verification must match a safely named npm script discovered from package.json. Allowed commands: ${choices}.`);
  }
  return selected;
}

function surfaceMarkers(stdout) {
  const markers = [];
  for (const rawLine of String(stdout ?? '').split(/\r?\n/)) {
    const line = rawLine.startsWith('# ') ? rawLine.slice(2) : rawLine;
    if (!line.startsWith(SURFACE_EVIDENCE_MARKER_PREFIX) || line.length > 8192 || markers.length >= 16) continue;
    try {
      const value = JSON.parse(line.slice(SURFACE_EVIDENCE_MARKER_PREFIX.length));
      if (
        value?.schemaVersion !== 1
        || !['storyId', 'signalId', 'profileId', 'entrypoint'].every((field) => typeof value[field] === 'string' && value[field].length > 0 && value[field].length <= 1000)
        || value.outcome !== 'passed'
      ) continue;
      markers.push({
        schemaVersion: 1,
        storyId: value.storyId,
        signalId: value.signalId,
        profileId: value.profileId,
        entrypoint: value.entrypoint,
        outcome: value.outcome,
      });
    } catch {
      // Malformed output is not evidence and is never returned verbatim.
    }
  }
  return markers;
}

function runVerification(scan, selected) {
  const result = runNpmScript(scan.root, selected.name);
  const qa = parseWorkUnitResults(result.stdout);
  return {
    command: selected.command,
    status: result.error || result.status !== 0 ? 'failed' : 'passed',
    exitCode: result.status ?? 1,
    markers: surfaceMarkers(result.stdout),
    outputDigest: sha256(`${result.stdout ?? ''}\0${result.stderr ?? ''}`),
    qaResults: qa.results,
    qaError: qa.error,
  };
}

const CLIENT_GOVERNANCE = clientGovernanceMatchers();

function nonUnitEvidencePath(relative) {
  return relative.startsWith('docs/') || relative.startsWith('.ai-governance/') || CLIENT_GOVERNANCE.isPath(relative);
}

function completionResult(scan, { mode, stagedFiles = [], paths, taskLevel, verificationCommand = null, reviewMode = null, approvalEvidence = null, approve = null, gitRoot = scan.root, workUnit: workUnitRelative = null }) {
  let { config, taskRoute, behaviorPaths, trustedBehaviorChange } = completionTaskRoute(scan, paths, taskLevel, gitRoot);
  let unit = workUnitRelative ? readWorkUnit(scan.root, workUnitRelative) : null;
  const unitEvidencePaths = unit ? [workUnitRelative, ...scan.files.filter((entry) => entry.type === 'file' && !nonUnitEvidencePath(entry.relative)).map((entry) => entry.relative), ...unit.scope.flatMap((group) => group.paths), ...unit.testCases.map((entry) => entry.testPath), ...unit.references.map((entry) => entry.path)] : [];
  const selectedVerification = verificationCommand ? discoveredVerification(scan, verificationCommand) : null;
  const governance = checkProject(scan);
  let projectVerification = { status: 'not-requested', command: null };
  let harvestBindingReason = null;
  if (selectedVerification && taskRoute.status === 'upgrade-required') {
    projectVerification = { status: 'skipped-after-task-route-failure', command: selectedVerification.command };
  } else if (selectedVerification && governance.ok) {
    const bindHarvest = taskRoute.status === 'verified' && ['L2', 'L3'].includes(taskRoute.declaredLevel);
    const before = bindHarvest ? verificationInputSnapshot(scan, paths, unitEvidencePaths) : null;
    let unitBefore = null;
    if (unit) try { unitBefore = workUnitVerificationBinding(scan.root, { ...scan, workUnitPath: workUnitRelative, approvalEvidence }, unit); } catch { unitBefore = { unavailable: true }; }
    projectVerification = runVerification(scan, selectedVerification);
    // Manual verification can mutate any path or the routing configuration. Re-read
    // both before claiming a final route; hook mode never runs project commands and
    // continues to use only its materialized index snapshot.
    paths = changedPaths(scan.root);
    ({ config, taskRoute, behaviorPaths, trustedBehaviorChange } = completionTaskRoute(scan, paths, taskLevel, gitRoot));
    if (before && projectVerification.status === 'passed') {
      let after;
      try {
        after = verificationInputSnapshot(scanProject(scan.root, { probeEnvironment: false }), before.paths ?? paths, unitEvidencePaths);
      } catch {
        after = { reason: 'product-change-evidence-unavailable' };
      }
      harvestBindingReason = before.reason ?? after.reason ?? (before.fingerprint !== after.fingerprint ? 'verification-input-changed' : null);
      if (unitBefore) try {
        const unitAfter = workUnitVerificationBinding(scan.root, { ...scanProject(scan.root, { probeEnvironment: false }), workUnitPath: workUnitRelative, approvalEvidence }, readWorkUnit(scan.root, workUnitRelative));
        if (unitBefore.unavailable || stableJson(unitBefore) !== stableJson(unitAfter)) harvestBindingReason = 'verification-input-changed';
      } catch { harvestBindingReason = 'verification-input-changed'; }
      projectVerification.inputEvidence = {
        status: harvestBindingReason ? 'unverified' : 'unchanged',
        beforeFingerprint: before.fingerprint ?? null,
        afterFingerprint: after.fingerprint ?? null,
      };
    }
  } else if (selectedVerification) {
    projectVerification = { status: 'skipped-after-governance-failure', command: selectedVerification.command };
  }
  // This reads final evidence after an explicitly requested verification command.
  // In hook mode scan.root is the materialized index, never the live worktree.
  const confirmedRiskSignals = [...new Set([...applicableRiskSignals(config, paths), ...(unit?.risks ?? [])])];
  if (unit) unit = readWorkUnit(scan.root, workUnitRelative);
  const professionalContext = trustedProfessionalTaskContext(scan.root, config, paths);
  const professionalBoundaries = [...professionalContext.professionalBoundaries];
  for (const boundary of unit?.professionalBoundaries ?? []) {
    const existing = professionalBoundaries.find((entry) => entry.id === boundary.id);
    if (existing && stableJson(existing) !== stableJson(boundary)) professionalContext.professionalGap = 'Work-unit cannot redefine the approved project professional boundary.';
    if (!existing) professionalBoundaries.push(boundary);
  }
  const taskApproval = evaluateTaskApproval(scan.root, {
    taskLevel: taskLevel ?? taskRoute.minimumLevel, reviewMode, plannedPaths: paths, approvalEvidence, approve,
    changeDigest: completionChangeDigest(gitRoot, scan.root, paths, mode, approvalEvidence, workUnitRelative),
    ...professionalContext,
    professionalBoundaries,
    workUnitDigest: unit ? workUnitPlanDigest(unit) : null,
    planDigest: readFlowPlanDigest(scan.root),
    confirmedRiskSignals,
    reviewEvidence: { confirmedRisk: confirmedRiskSignals.length > 0, publicContract: confirmedRiskSignals.includes('public-api'), externalAction: confirmedRiskSignals.includes('external-side-effect') },
    trustedBehaviorChange,
    // Paths and approved scope mappings determine task-local risk and review applicability.
  });
  const routeAccepted = taskRoute.status === 'verified' || (taskRoute.status === 'unverified-declaration' && ['L0', 'L1'].includes(taskRoute.minimumLevel));
  const memoryScan = { ...(unit ? scanProject(scan.root, { probeEnvironment: false }) : scan), memoryGitRoot: gitRoot, workUnitPath: workUnitRelative, approvalEvidence };
  const needsWorkUnit = ['L2', 'L3'].includes(taskRoute.declaredLevel ?? taskRoute.minimumLevel) && behaviorPaths.length > 0;
  const memory = { issues: config?.features?.knowledge || unit ? memoryIssues(scan.root, memoryScan, paths) : [] };
  memory.status = memory.issues.length ? 'blocked' : config?.features?.knowledge || unit ? 'checked' : 'disabled';
  if (unit && !selectedVerification && unit.verification.evidence) projectVerification = replayWorkUnitVerification(scan.root, memoryScan, unit);
  const surfaceVerification = evaluateSurfaceVerification(scan, projectVerification);
  const workUnit = unit ? checkWorkUnit(scan.root, unit, { scan: memoryScan, config, changedPaths: paths, behaviorPaths, taskApproval, memory, verification: projectVerification })
    : { ok: !needsWorkUnit, status: needsWorkUnit ? 'missing' : 'not-required', issues: needsWorkUnit ? ['L2/L3 production delivery requires --work-unit <safe-relative-json>.'] : [] };
  if (unit && (unit.taskLevel !== taskApproval.plan?.taskLevel || unit.reviewMode !== taskApproval.review?.mode)) { workUnit.ok = false; workUnit.status = 'blocked'; workUnit.issues.push('work-unit route differs from the final approved task route.'); }
  if (unit && selectedVerification && projectVerification.status === 'passed' && projectVerification.inputEvidence?.status === 'unchanged') {
    workUnit.recordedEvidence = recordWorkUnitVerification(scan.root, memoryScan, unit, projectVerification);
    workUnit.recordedResults = projectVerification.qaResults;
  }
  const ok = routeAccepted && taskApproval.ok && workUnit.ok && governance.ok && memory.issues.length === 0 && ['not-requested', 'passed'].includes(projectVerification.status) && surfaceVerification.status !== 'blocked';
  const productionReadiness = evaluateProductionReadiness(scan);
  const harvestInput = { taskRoute, changedPaths: paths, verification: projectVerification };
  const changeEvidence = harvestBindingReason ? { paths: [], reason: harvestBindingReason }
    : taskApproval.ok && assessHarvestEligibility(harvestInput).eligible ? capabilityChangedPaths(scan, paths) : { paths };
  harvestInput.changedPaths = changeEvidence.paths;
  const harvest = completionCapabilityHarvestSummary(config, scan, taskApproval.ok ? harvestInput : { ...harvestInput, changedPaths: [] });
  if (changeEvidence.reason && taskRoute.status !== 'upgrade-required') harvest.reason = changeEvidence.reason;
  if (!taskApproval.ok && taskRoute.status === 'verified') {
    Object.assign(harvest, { status: 'skipped', eligible: false, reason: changeEvidence.reason ?? `task-approval-${taskApproval.status}`, candidates: [] });
  }
  if (!workUnit.ok && harvest.eligible) Object.assign(harvest, { status: 'skipped', eligible: false, reason: 'work-unit-incomplete', candidates: [] });
  const claimBoundary = 'A successful completion gate proves managed governance structure and at most one explicitly selected project command; it does not establish production readiness.';
  return {
    schemaVersion: 1,
    mode,
    target: scan.root,
    stagedFiles,
    ok,
    taskRoute,
    taskApproval,
    memory,
    workUnit,
    productionReadiness,
    surfaceVerification,
    claimBoundary,
    governance,
    projectVerification,
    harvest,
    generation: {
      status: 'manual-only',
      commands: ['aicg sync .', 'aicg harvest . --dry-run', 'aicg promote ...'],
      boundary: 'Completion validation never invents semantic docs/memory, writes Skills, or stages files. Use an explicit approved generation command for those mutations.',
    },
    boundaries: [
      claimBoundary,
      'It does not prove code-review quality, semantic memory accuracy, client loading, or every business behavior.',
    ],
  };
}

export function runCompletion(target, { fromGitHook = false, verificationCommand = null, taskLevel = null, reviewMode = null, approvalEvidence = null, approve = null, workUnit = null } = {}) {
  if (fromGitHook) {
    taskLevel ??= process.env.AICG_TASK_LEVEL ?? null;
    reviewMode ??= process.env.AICG_REVIEW_MODE ?? null;
    approvalEvidence ??= process.env.AICG_APPROVAL_EVIDENCE ?? null;
    approve ??= process.env.AICG_APPROVE ?? null;
    workUnit ??= process.env.AICG_WORK_UNIT ?? null;
    if (approvalEvidence !== null && (typeof approvalEvidence !== 'string' || approvalEvidence.length > 4096 || !isSafeRelative(approvalEvidence))) throw usageError('AICG_APPROVAL_EVIDENCE must be a safe repository-relative path.');
    if (approve !== null && (typeof approve !== 'string' || !/^[a-f0-9]{64}$/.test(approve))) throw usageError('AICG_APPROVE must be a SHA256 plan hash.');
  }
  validateTaskLevel(taskLevel);
  validateReviewMode(reviewMode);
  if (workUnit !== null) workUnitPath(workUnit);
  if (!fromGitHook) {
    const root = resolveGitRepository(target);
    const paths = changedPaths(root);
    const scan = scanProject(target, { probeEnvironment: false });
    return completionResult(scan, { mode: 'manual', paths, taskLevel, verificationCommand, reviewMode, approvalEvidence, approve, workUnit });
  }
  if (verificationCommand) throw usageError('--from-git-hook cannot run a project verification command. Run aicg complete manually with --verify instead.');
  const root = resolveGitRepository(target);
  git(root, ['rev-parse', '--verify', 'HEAD^{commit}']);
  const paths = stagedPaths(root);
  return withIndexSnapshot(root, (snapshot) => completionResult(scanProject(snapshot, { probeEnvironment: false }), {
    mode: 'git-pre-commit',
    stagedFiles: paths,
    paths,
    taskLevel,
    reviewMode,
    approvalEvidence,
    approve,
    gitRoot: root,
    workUnit,
  }));
}
