import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { checkProject, evaluateCompletionTaskRoute, validateConfig, validateTaskLevel } from '../governance/index.mjs';
import { runGit, runNpmScript } from '../../adapters/process/index.mjs';
import { assertNoLinkAncestor, readJson, sameSnapshot, snapshotPath } from '../../adapters/filesystem/index.mjs';
import { CONFIG_PATH, PACKAGE_ROOT, TOOL_VERSION } from '../../constants.mjs';
import { scanProject, SURFACE_EVIDENCE_MARKER_PREFIX, verificationNpmCommands } from '../repository/index.mjs';
import { writeAtomicFile } from '../../adapters/filesystem/index.mjs';
import { usageError } from '../../kernel/index.mjs';
import { sha256, stableJson } from '../../shared/index.mjs';
import { evaluateProductionReadiness } from './production-readiness.mjs';
import { evaluateSurfaceVerification } from './surface-verification.mjs';
import { assessHarvestEligibility, capabilitySourceChanged, completionCapabilityHarvestSummary, isProductionCapabilityPath } from '../capabilities/index.mjs';

export const PRE_COMMIT_HOOK_MARKER = 'ai-code-governance:pre-commit-v1';

function git(root, args) {
  const result = runGit(root, args, { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
  if (result.error || result.status !== 0) {
    throw usageError(`Git command failed while preparing the completion gate: git ${args.join(' ')}.`);
  }
  return result.stdout.trim();
}

function resolveGitRepository(target) {
  const root = path.resolve(target);
  const gitRoot = git(root, ['rev-parse', '--show-toplevel']);
  return path.resolve(gitRoot);
}

function hookPathFor(root) {
  const hooks = git(root, ['rev-parse', '--git-path', 'hooks']);
  return path.resolve(root, hooks, 'pre-commit');
}

function shellQuote(value) {
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

function hookContent() {
  const node = shellQuote(process.execPath);
  const entrypoint = shellQuote(path.join(PACKAGE_ROOT, 'bin', 'aicg.js'));
  return `#!/bin/sh\n# ${PRE_COMMIT_HOOK_MARKER}\n# Generated by AI Code Governance. Reinstall with aicg hook install after relocating the CLI.\nset -eu\nrepo_root=$(git rev-parse --show-toplevel)\nexec ${node} ${entrypoint} complete "$repo_root" --from-git-hook\n`;
}

function hookState(hookPath) {
  const snapshot = snapshotPath(hookPath);
  if (snapshot.kind === 'missing') return { status: 'not-installed', snapshot };
  if (snapshot.kind !== 'file') return { status: 'conflict', snapshot };
  const content = fs.readFileSync(hookPath, 'utf8');
  return content.includes(PRE_COMMIT_HOOK_MARKER)
    ? { status: 'managed', snapshot }
    : { status: 'conflict', snapshot };
}

function digest(value) {
  return sha256(stableJson(value));
}

export function inspectCommitHook(target) {
  const root = resolveGitRepository(target);
  const hookPath = hookPathFor(root);
  const state = hookState(hookPath);
  return { targetRoot: root, hookPath, hookStatus: state.status, before: state.snapshot };
}

export function prepareCommitHookInstall(target) {
  const inspected = inspectCommitHook(target);
  const { targetRoot: root, hookPath, hookStatus, before } = inspected;
  if (hookStatus === 'conflict') {
    throw usageError(`Refuse to replace the existing pre-commit hook at ${hookPath}. Preserve it or integrate aicg manually.`);
  }
  const base = {
    schemaVersion: 1,
    intent: 'governance.install-precommit',
    targetRoot: root,
    hookPath,
    before,
    hookStatus,
    contentSha256: sha256(hookContent()),
    toolVersion: TOOL_VERSION,
    requiredPermissions: ['write-git-hook'],
    verification: 'git-pre-commit-staged-governance-check',
    boundaries: [
      'The generated hook validates the Git index snapshot at commit time; it does not run on ordinary conversation turns.',
      'The hook never writes project files, stages files, or synthesizes business memory or Skills.',
      'Project behavior commands remain explicit manual aicg complete --verify invocations until separately configured and evidenced.',
    ],
  };
  return { ...base, planHash: digest(base) };
}

export function assertCommitHookPlanFresh(plan) {
  if (!plan || plan.schemaVersion !== 1 || plan.intent !== 'governance.install-precommit' || typeof plan.targetRoot !== 'string' || typeof plan.hookPath !== 'string') {
    throw usageError('Commit-hook installation plan is invalid. Generate a new plan.');
  }
  const root = resolveGitRepository(plan.targetRoot);
  if (root !== plan.targetRoot || hookPathFor(root) !== plan.hookPath) throw usageError('Commit-hook installation plan targets a different Git repository. Generate a new plan.');
  const state = hookState(plan.hookPath);
  if (state.status === 'conflict' || !sameSnapshot(state.snapshot, plan.before)) {
    throw usageError('Commit-hook installation plan is stale because the existing hook changed. Generate a new plan.');
  }
  const { planHash, ...base } = plan;
  if (planHash !== digest(base) || plan.contentSha256 !== sha256(hookContent())) {
    throw usageError('Commit-hook installation plan is invalid or was created by a different CLI build. Generate a new plan.');
  }
  return true;
}

export function installCommitHook(plan) {
  assertCommitHookPlanFresh(plan);
  writeAtomicFile(plan.hookPath, hookContent(), 0o755);
  return { hookPath: plan.hookPath, status: 'installed', marker: PRE_COMMIT_HOOK_MARKER };
}

function stagedPaths(root) {
  const result = runGit(root, ['diff', '--cached', '--name-only', '-z', '--no-renames'], { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
  if (result.error || result.status !== 0) throw usageError('Cannot read the Git index for the pre-commit completion gate.');
  return result.stdout.split('\0').filter(Boolean).sort((left, right) => left.localeCompare(right));
}

function changedPaths(root) {
  const paths = [];
  // Disable rename collapsing so moving a sensitive source into docs cannot hide its removal.
  for (const args of [
    ['diff', '--cached', '--name-only', '-z', '--no-renames', 'HEAD'],
    ['diff', '--name-only', '-z', '--no-renames'],
    ['ls-files', '--others', '--exclude-standard', '-z'],
  ]) {
    const result = runGit(root, args, { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
    if (result.error || result.status !== 0) throw usageError('Cannot read changed paths for the completion gate.');
    paths.push(...result.stdout.split('\0').filter(Boolean));
  }
  return [...new Set(paths)].sort((left, right) => left.localeCompare(right));
}

function completionTaskRoute(scan, paths, taskLevel) {
  let config;
  try {
    assertNoLinkAncestor(scan.root, CONFIG_PATH);
    config = validateConfig(readJson(path.join(scan.root, CONFIG_PATH)));
  } catch (error) {
    throw usageError(`Cannot read task routing configuration for the completion gate: ${error.message}`);
  }
  return { config, taskRoute: evaluateCompletionTaskRoute(paths, config, taskLevel) };
}

function capabilityChangedPaths(scan, paths) {
  const sources = new Map(scan.files.filter((file) => file.type === 'file' && file.contentScannable !== false).map((file) => [file.relative, file]));
  const changed = [];
  const unavailable = { paths: [], reason: 'product-change-evidence-unavailable' };
  for (const relative of paths) {
    if (!isProductionCapabilityPath(relative) || !sources.has(relative)) continue;
    const before = runGit(scan.root, ['show', `HEAD:${relative}`], { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
    if (before.error) return unavailable;
    if (before.status !== 0) {
      // Distinguish an added source from an unreadable tracked blob.
      const entry = runGit(scan.root, ['ls-tree', '-z', 'HEAD', '--', relative], { timeout: 15000, maxBuffer: 2 * 1024 * 1024 });
      if (entry.error || entry.status !== 0 || entry.stdout.length > 0) return unavailable;
    }
    try {
      assertNoLinkAncestor(scan.root, relative);
      const after = fs.readFileSync(sources.get(relative).absolute, 'utf8');
      if (before.status !== 0 || capabilitySourceChanged(before.stdout, after)) changed.push(relative);
    } catch {
      return unavailable;
    }
  }
  return { paths: changed };
}

function verificationInputSnapshot(scan, knownPaths = []) {
  const unavailable = { reason: 'product-change-evidence-unavailable' };
  if (scan.scanBudget?.complete !== true) return unavailable;
  const relevant = (relative) => isProductionCapabilityPath(relative) || relative === 'package.json' || relative.endsWith('/package.json');
  try {
    const index = git(scan.root, ['ls-files', '--stage', '-z']).split('\0').filter(Boolean).map((entry) => {
      const separator = entry.indexOf('\t');
      if (separator < 0) throw new Error('Invalid index record.');
      return { path: entry.slice(separator + 1), entry: entry.slice(0, separator) };
    }).filter((entry) => relevant(entry.path));
    const paths = [...new Set([...knownPaths, ...scan.files.map((file) => file.relative), ...index.map((entry) => entry.path)])]
      .filter(relevant).sort((left, right) => left.localeCompare(right));
    const sources = paths.map((relative) => {
      assertNoLinkAncestor(scan.root, relative, { allowFinalLink: true });
      return { path: relative, snapshot: snapshotPath(path.join(scan.root, relative)) };
    });
    const fields = git(scan.root, ['diff', '--name-status', '-z', '--no-renames', 'HEAD']).split('\0').filter(Boolean);
    if (fields.length % 2 !== 0) return unavailable;
    const diff = [];
    for (let index = 0; index < fields.length; index += 2) {
      if (relevant(fields[index + 1])) diff.push({ status: fields[index], path: fields[index + 1] });
    }
    return { paths, fingerprint: digest({ head: git(scan.root, ['rev-parse', 'HEAD']), sources, index, diff }) };
  } catch {
    return unavailable;
  }
}

function withIndexSnapshot(root, action) {
  const snapshot = fs.mkdtempSync(path.join(os.tmpdir(), 'aicg-index-snapshot-'));
  try {
    const prefix = `${snapshot}${path.sep}`;
    const result = runGit(root, ['checkout-index', '--all', `--prefix=${prefix}`], { timeout: 30000, maxBuffer: 4 * 1024 * 1024 });
    if (result.error || result.status !== 0) throw usageError('Cannot materialize the Git index for the pre-commit completion gate.');
    return action(snapshot);
  } finally {
    fs.rmSync(snapshot, { recursive: true, force: true });
  }
}

const NPM_SHORTHANDS = new Map([
  ['npm test', 'test'],
]);

function safeNpmVerifications(scan) {
  return verificationNpmCommands(scan.commands)
    .sort((left, right) => left.command.localeCompare(right.command));
}

function discoveredVerification(scan, requestedCommand) {
  const allowed = safeNpmVerifications(scan);
  const shorthandName = NPM_SHORTHANDS.get(requestedCommand);
  const canonicalCommand = shorthandName ? `npm run ${shorthandName}` : requestedCommand;
  const selected = allowed.find((candidate) => candidate.command === canonicalCommand);
  if (!selected) {
    const choices = allowed.length > 0 ? allowed.map((candidate) => candidate.command).join(', ') : '(none discovered)';
    throw usageError(`Completion verification must match a safely named npm script discovered from package.json. Allowed commands: ${choices}.`);
  }
  return selected;
}

function surfaceMarkers(stdout) {
  const markers = [];
  for (const line of String(stdout ?? '').split(/\r?\n/)) {
    if (!line.startsWith(SURFACE_EVIDENCE_MARKER_PREFIX) || line.length > 8192 || markers.length >= 16) continue;
    try {
      const value = JSON.parse(line.slice(SURFACE_EVIDENCE_MARKER_PREFIX.length));
      if (
        value?.schemaVersion !== 1
        || !['storyId', 'signalId', 'profileId', 'entrypoint'].every((field) => typeof value[field] === 'string' && value[field].length > 0 && value[field].length <= 1000)
        || value.outcome !== 'passed'
      ) continue;
      markers.push({
        schemaVersion: 1,
        storyId: value.storyId,
        signalId: value.signalId,
        profileId: value.profileId,
        entrypoint: value.entrypoint,
        outcome: value.outcome,
      });
    } catch {
      // Malformed output is not evidence and is never returned verbatim.
    }
  }
  return markers;
}

function runVerification(scan, selected) {
  const result = runNpmScript(scan.root, selected.name);
  return {
    command: selected.command,
    status: result.error || result.status !== 0 ? 'failed' : 'passed',
    exitCode: result.status ?? 1,
    markers: surfaceMarkers(result.stdout),
    outputDigest: sha256(`${result.stdout ?? ''}\0${result.stderr ?? ''}`),
  };
}

function completionResult(scan, { mode, stagedFiles = [], paths, taskLevel, verificationCommand = null }) {
  let { config, taskRoute } = completionTaskRoute(scan, paths, taskLevel);
  const selectedVerification = verificationCommand ? discoveredVerification(scan, verificationCommand) : null;
  const governance = checkProject(scan);
  let projectVerification = { status: 'not-requested', command: null };
  let harvestBindingReason = null;
  if (selectedVerification && taskRoute.status === 'upgrade-required') {
    projectVerification = { status: 'skipped-after-task-route-failure', command: selectedVerification.command };
  } else if (selectedVerification && governance.ok) {
    const bindHarvest = taskRoute.status === 'verified' && ['L2', 'L3'].includes(taskRoute.declaredLevel);
    const before = bindHarvest ? verificationInputSnapshot(scan, paths) : null;
    projectVerification = runVerification(scan, selectedVerification);
    // Manual verification can mutate any path or the routing configuration. Re-read
    // both before claiming a final route; hook mode never runs project commands and
    // continues to use only its materialized index snapshot.
    paths = changedPaths(scan.root);
    ({ config, taskRoute } = completionTaskRoute(scan, paths, taskLevel));
    if (before && projectVerification.status === 'passed') {
      let after;
      try {
        after = verificationInputSnapshot(scanProject(scan.root, { probeEnvironment: false }), before.paths ?? paths);
      } catch {
        after = { reason: 'product-change-evidence-unavailable' };
      }
      harvestBindingReason = before.reason ?? after.reason ?? (before.fingerprint !== after.fingerprint ? 'verification-input-changed' : null);
      projectVerification.inputEvidence = {
        status: harvestBindingReason ? 'unverified' : 'unchanged',
        beforeFingerprint: before.fingerprint ?? null,
        afterFingerprint: after.fingerprint ?? null,
      };
    }
  } else if (selectedVerification) {
    projectVerification = { status: 'skipped-after-governance-failure', command: selectedVerification.command };
  }
  const surfaceVerification = evaluateSurfaceVerification(scan, projectVerification);
  const ok = taskRoute.status !== 'upgrade-required' && governance.ok && ['not-requested', 'passed'].includes(projectVerification.status) && surfaceVerification.status !== 'blocked';
  const productionReadiness = evaluateProductionReadiness(scan);
  const harvestInput = { taskRoute, changedPaths: paths, verification: projectVerification };
  const changeEvidence = harvestBindingReason ? { paths: [], reason: harvestBindingReason }
    : assessHarvestEligibility(harvestInput).eligible ? capabilityChangedPaths(scan, paths) : { paths };
  harvestInput.changedPaths = changeEvidence.paths;
  const harvest = completionCapabilityHarvestSummary(config, scan, harvestInput);
  if (changeEvidence.reason && taskRoute.status !== 'upgrade-required') harvest.reason = changeEvidence.reason;
  const claimBoundary = 'A successful completion gate proves managed governance structure and at most one explicitly selected project command; it does not establish production readiness.';
  return {
    schemaVersion: 1,
    mode,
    target: scan.root,
    stagedFiles,
    ok,
    taskRoute,
    productionReadiness,
    surfaceVerification,
    claimBoundary,
    governance,
    projectVerification,
    harvest,
    generation: {
      status: 'manual-only',
      commands: ['aicg sync .', 'aicg harvest . --dry-run', 'aicg promote ...'],
      boundary: 'Completion validation never invents semantic docs/memory, writes Skills, or stages files. Use an explicit approved generation command for those mutations.',
    },
    boundaries: [
      claimBoundary,
      'It does not prove code-review quality, semantic memory accuracy, client loading, or every business behavior.',
    ],
  };
}

export function runCompletion(target, { fromGitHook = false, verificationCommand = null, taskLevel = null } = {}) {
  validateTaskLevel(taskLevel);
  if (!fromGitHook) {
    const root = resolveGitRepository(target);
    const paths = changedPaths(root);
    const scan = scanProject(target, { probeEnvironment: false });
    return completionResult(scan, { mode: 'manual', paths, taskLevel, verificationCommand });
  }
  if (verificationCommand) throw usageError('--from-git-hook cannot run a project verification command. Run aicg complete manually with --verify instead.');
  const root = resolveGitRepository(target);
  git(root, ['rev-parse', '--verify', 'HEAD^{commit}']);
  const paths = stagedPaths(root);
  return withIndexSnapshot(root, (snapshot) => completionResult(scanProject(snapshot, { probeEnvironment: false }), {
    mode: 'git-pre-commit',
    stagedFiles: paths,
    paths,
    taskLevel,
  }));
}
