import { resolveAgents, selectedSkillDirectories } from '../../catalogs/index.mjs';
import { skillAdapterContent } from '../../shared/index.mjs';
import { canonicalPath } from './layout.mjs';

/**
 * Client projections are thin, generated adapters over the single docs/ai canon. The agent
 * registry decides which clients are selected and where each client discovers Skills; this
 * module decides the small per-client entry template. No other governance module branches
 * on a specific client id.
 */

/** Bump when a projection template changes so Task 3 receipts can detect a stale hash. */
export const PROJECTION_TEMPLATE_VERSION = 1;

/** Non-enumerable-by-contract opt-in marker so a compiler definition keeps its public shape. */
export const SKILL_ADAPTER_FLAG = Symbol('skillAdapterFlag');

export const PROJECTION_TEMPLATES = Object.freeze({
  'claude-code': 'template:claude-entrypoint',
  cursor: 'template:cursor-rule',
  'github-copilot': 'template:copilot-instructions',
});

/** Stable source/template reference recorded on a generated projection for receipts. */
export function projectionTemplate(clientId, surfaceId = 'repository-instructions') {
  return Object.freeze({ clientId, surfaceId, template: PROJECTION_TEMPLATES[clientId] ?? null, templateVersion: PROJECTION_TEMPLATE_VERSION });
}

function governanceCommand(config, args = '') {
  const suffix = args ? ' ' + args : '';
  return (config.invocationMode === 'project-local' ? 'npm exec -- aicg' : 'aicg') + suffix;
}

function selectedClients(config) {
  return new Set(config.clients ?? []);
}

function ticket() {
  return String.fromCharCode(96);
}

function claudeBody(zh) {
  return zh
    ? '@AGENTS.md\n\nClaude Code 通过上述原生导入加载共享的项目治理。\n'
    : '@AGENTS.md\n\nClaude Code loads the shared project governance through the native import above.\n';
}

function cursorBody(config) {
  const canon = config.canonicalRoot ?? 'docs/ai';
  const alwaysRule = canonicalPath('docs/ai/rules/00_always.mdc', config.governanceFootprint ?? 'compact');
  const sync = governanceCommand(config, 'sync .');
  const T = ticket();
  if (config.artifactLanguage === 'zh-CN') {
    return [
      '---',
      'description: 将 Cursor 路由到仓库的 AI 治理正典。',
      'alwaysApply: true',
      '---',
      '',
      '<!-- Generated by AI Code Governance. Do not edit this adapter directly. -->',
      '',
      '读取 ' + T + 'AGENTS.md' + T + '，随后遵循 ' + canon + '/context-map.yaml 和 ' + alwaysRule + '。客户端专属适配器由工具生成；修改正典治理后运行 ' + T + sync + T + '。',
      '',
    ].join('\n');
  }
  return [
    '---',
    'description: Route Cursor to the repository AI governance canon.',
    'alwaysApply: true',
    '---',
    '',
    '<!-- Generated by AI Code Governance. Do not edit this adapter directly. -->',
    '',
    'Read ' + T + 'AGENTS.md' + T + ', then follow ' + T + canon + '/context-map.yaml' + T + ' and ' + T + alwaysRule + T + '. Client-specific adapters are generated; change canonical governance and run ' + T + sync + T + '.',
    '',
  ].join('\n');
}

function copilotBody(config) {
  const canon = config.canonicalRoot ?? 'docs/ai';
  const alwaysRule = canonicalPath('docs/ai/rules/00_always.mdc', config.governanceFootprint ?? 'compact');
  const sync = governanceCommand(config, 'sync .');
  const check = governanceCommand(config, 'check .');
  const T = ticket();
  if (config.artifactLanguage === 'zh-CN') {
    return [
      '# GitHub Copilot AI 编码治理',
      '',
      '本区块由 ' + T + 'aicg' + T + ' 管理，区块外的项目专属内容会保留。',
      '',
      '- 共享入口：[AGENTS.md](AGENTS.md)',
      '- 治理正典：[' + canon + '/](' + canon + '/)',
      '- 从 [' + canon + '/context-map.yaml](' + canon + '/context-map.yaml) 的 ' + T + 'ordinary' + T + ' 配置开始。',
      '- 常驻规则：[' + alwaysRule + '](' + alwaysRule + ')',
      '- 本适配器只引用正典，不复制规则；修改正典后运行 ' + T + sync + T + '，不要直接编辑适配器。',
      '- Copilot 各运行表面对仓库指令与 AGENTS.md 的读取范围不同；请直接读取本文件与正典。检查命令：' + T + check + T + '。',
      '',
    ].join('\n');
  }
  return [
    '# GitHub Copilot AI coding governance',
    '',
    'This block is managed by ' + T + 'aicg' + T + '. Project-specific content outside this block is preserved.',
    '',
    '- Shared entrypoint: [AGENTS.md](AGENTS.md)',
    '- Canonical governance: [' + canon + '/](' + canon + '/)',
    '- Start with the ' + T + 'ordinary' + T + ' profile in [' + canon + '/context-map.yaml](' + canon + '/context-map.yaml).',
    '- Always-on rule: [' + alwaysRule + '](' + alwaysRule + ')',
    '- This adapter references the canon instead of copying rules; change canonical governance and run ' + T + sync + T + '. Do not edit generated adapters.',
    '- Copilot surfaces differ in how they read repository instructions and AGENTS.md; read this file and the canon directly. Check with ' + T + check + T + '.',
    '',
  ].join('\n');
}

function entryProjection(config, clientId) {
  if (clientId === 'claude-code') {
    return {
      id: 'CLAUDE.md',
      path: 'CLAUDE.md',
      capability: 'integration',
      activation: 'selected',
      requires: [(value) => selectedClients(value).has('claude-code')],
      ownership: 'managed-block',
      routeProfiles: [],
      gateAssertions: ['claude-adapter'],
      build: () => ({
        path: 'CLAUDE.md',
        content: claudeBody(config.artifactLanguage === 'zh-CN'),
        ownership: 'managed-block',
        kind: 'adapter',
        source: 'AGENTS.md',
      }),
    };
  }
  if (clientId === 'cursor') {
    const source = canonicalPath('docs/ai/rules/00_always.mdc', config.governanceFootprint ?? 'compact');
    return {
      id: '.cursor/rules/ai-code-governance.mdc',
      path: '.cursor/rules/ai-code-governance.mdc',
      capability: 'integration',
      activation: 'selected',
      requires: [(value) => selectedClients(value).has('cursor')],
      ownership: 'full',
      routeProfiles: [],
      gateAssertions: ['cursor-adapter'],
      build: () => ({ path: '.cursor/rules/ai-code-governance.mdc', content: cursorBody(config), ownership: 'full', kind: 'adapter', source }),
    };
  }
  if (clientId === 'github-copilot') {
    return {
      id: '.github/copilot-instructions.md',
      path: '.github/copilot-instructions.md',
      capability: 'integration',
      activation: 'selected',
      requires: [(value) => selectedClients(value).has('github-copilot')],
      ownership: 'managed-block',
      routeProfiles: [],
      gateAssertions: ['copilot-adapter'],
      build: () => ({ path: '.github/copilot-instructions.md', content: copilotBody(config), ownership: 'managed-block', kind: 'adapter', source: 'AGENTS.md' }),
    };
  }
  return null;
}

function canonicalSkillContent(artifact, selected) {
  if (typeof artifact.content === 'string') return artifact.content;
  if (typeof artifact.build === 'function') {
    const built = artifact.build(selected);
    return typeof built === 'string' ? built : built?.content;
  }
  return null;
}

function adapterEligible(artifact) {
  if (!artifact || typeof artifact.path !== 'string') return false;
  if (!artifact.path.startsWith('docs/ai/skills/') || !artifact.path.endsWith('/SKILL.md')) return false;
  if (artifact.kind === 'skill-management-skill') return false;
  // A rendered artifact carries content; a compiler definition opts in with the symbol flag.
  return artifact[SKILL_ADAPTER_FLAG] === true || typeof artifact.content === 'string';
}

function skillAdapterDefinition(source, adapterPath) {
  return {
    id: adapterPath,
    path: adapterPath,
    capability: source.capability ?? 'integration',
    activation: source.activation ?? 'selected',
    requires: source.requires ?? [],
    ownership: 'full',
    routeProfiles: [],
    gateAssertions: [],
    build: (selected) => {
      const content = canonicalSkillContent(source, selected);
      return {
        path: adapterPath,
        content: skillAdapterContent(source.path, content),
        ownership: 'full',
        kind: 'adapter-skill',
        source: source.path,
      };
    },
  };
}

/**
 * Derive the thin client projections from the agent registry and the canonical artifacts.
 * canonicalArtifacts may be compiler definitions (with build functions) or rendered
 * artifacts (with content).
 */
export function clientProjectionDefinitions(config, canonicalArtifacts = []) {
  const definitions = [];
  for (const agent of resolveAgents(config.clients ?? [])) {
    const projection = entryProjection(config, agent.id);
    if (projection) definitions.push(projection);
  }
  const skillDirectories = selectedSkillDirectories(config.clients ?? []);
  const adapters = [];
  for (const artifact of canonicalArtifacts) {
    if (!adapterEligible(artifact)) continue;
    const suffix = artifact.path.slice('docs/ai/skills/'.length);
    for (const directory of skillDirectories) adapters.push(skillAdapterDefinition(artifact, directory + '/' + suffix));
  }
  return [...definitions, ...adapters];
}
