import { declaredSkillDirectories, loadCapabilityRegistry } from '../../catalogs/index.mjs';
import { loadTechnicalStandardRegistry } from '../standards/index.mjs';

/**
 * First-party generated Skill families.
 *
 * Ordinary sync is zero-delete, so a repository generated by an earlier template keeps Skills the
 * current plan no longer selects (retired process Skills, a project-convention candidate whose
 * evidence changed, a stack standard that is no longer chosen). They are AICG's own output, so
 * post-apply verification must report a cleanup warning instead of an "unmanaged executable
 * governance artifact" error, and `sync --prune` must keep authority over them.
 */
export const RETIRED_PROCESS_SKILL_IDS = [
  'project-flow',
  'requirements',
  'design',
  'plan',
  'delivery-loop',
  'delivery-decomposition',
  'delivery-assignment',
  'delivery-development',
  'delivery-test-authoring',
  'delivery-local-test',
  'delivery-report',
  'delivery-fix-loop',
  'team-orchestrator',
];

// Suffix families AICG generates under a client Skill directory. Enumerated explicitly; a new
// first-party family must be added here so a leftover is recognized rather than reported as
// user-authored executable governance.
const FIRST_PARTY_SUFFIX_PREFIXES = [
  // Current one-level client projections whose names are config-driven, so they cannot be
  // enumerated here. `standard-` is deliberately absent: it is enumerated exactly from the
  // packaged registry below, because a bare prefix would wrongly claim a user Skill named
  // `standard-...` as AICG output.
  'capability-',
  'convention-',
  'business-constraints/',
  'brownfield-understanding/',
  'brownfield-enrichment/',
  'skill-discovery/',
  // Legacy grouped projections an earlier template wrote; ordinary sync is zero-delete, so
  // prune must still recognize them as AICG's own output.
  'project-conventions/',
  'standards/',
  'project/',
];

// Computed on first use, not at module load: loading the technical-standard registry while the
// module graph is still initializing trips its own top-level constants.
let firstPartySuffixes = null;
function firstPartySuffixSet() {
  if (firstPartySuffixes) return firstPartySuffixes;
  firstPartySuffixes = new Set();
  for (const pack of loadCapabilityRegistry().packs) firstPartySuffixes.add(pack.id + '/SKILL.md');
  for (const id of RETIRED_PROCESS_SKILL_IDS) firstPartySuffixes.add(id + '/SKILL.md');
  for (const standard of loadTechnicalStandardRegistry().standards) firstPartySuffixes.add('standard-' + standard.id + '/SKILL.md');
  return firstPartySuffixes;
}

function isFirstPartySuffix(suffix) {
  if (!suffix.endsWith('/SKILL.md')) return false;
  if (firstPartySuffixSet().has(suffix)) return true;
  if (suffix.startsWith('development-')) return true;
  return FIRST_PARTY_SUFFIX_PREFIXES.some((prefix) => suffix.startsWith(prefix));
}

/** True when a canonical or adapter Skill path belongs to a first-party AICG Skill family. */
export function isFirstPartyGeneratedSkill(relative) {
  if (typeof relative !== 'string') return false;
  if (relative.startsWith('docs/ai/skills/')) return isFirstPartySuffix(relative.slice('docs/ai/skills/'.length));
  for (const directory of declaredSkillDirectories()) {
    if (relative.startsWith(directory + '/')) return isFirstPartySuffix(relative.slice(directory.length + 1));
  }
  return false;
}

/** Canonical retired Skill paths. */
export function retiredCanonicalSkillPaths() {
  return RETIRED_PROCESS_SKILL_IDS.map((id) => 'docs/ai/skills/' + id + '/SKILL.md');
}
