import { declaredSkillDirectories, loadCapabilityRegistry } from '../../catalogs/index.mjs';

/**
 * First-party generated Skill families.
 *
 * Ordinary sync is zero-delete, so a repository generated by an earlier template keeps Skills the
 * current plan no longer selects (retired process Skills, a project-convention candidate whose
 * evidence changed, a stack standard that is no longer chosen). They are AICG's own output, so
 * post-apply verification must report a cleanup warning instead of an "unmanaged executable
 * governance artifact" error, and `sync --prune` must keep authority over them.
 */
export const RETIRED_PROCESS_SKILL_IDS = [
  'project-flow',
  'requirements',
  'design',
  'plan',
  'delivery-loop',
  'delivery-decomposition',
  'delivery-assignment',
  'delivery-development',
  'delivery-test-authoring',
  'delivery-local-test',
  'delivery-report',
  'delivery-fix-loop',
  'team-orchestrator',
];

// Suffix families AICG generates under a client Skill directory. Enumerated explicitly; a new
// first-party family must be added here so a leftover is recognized rather than reported as
// user-authored executable governance.
const FIRST_PARTY_SUFFIX_PREFIXES = [
  'project-conventions/',
  'standards/',
  'project/',
  'business-constraints/',
  'brownfield-understanding/',
  'brownfield-enrichment/',
  'skill-discovery/',
];

const FIRST_PARTY_SUFFIXES = new Set();
for (const pack of loadCapabilityRegistry().packs) FIRST_PARTY_SUFFIXES.add(pack.id + '/SKILL.md');
for (const id of RETIRED_PROCESS_SKILL_IDS) FIRST_PARTY_SUFFIXES.add(id + '/SKILL.md');

function isFirstPartySuffix(suffix) {
  if (!suffix.endsWith('/SKILL.md')) return false;
  if (FIRST_PARTY_SUFFIXES.has(suffix)) return true;
  if (suffix.startsWith('development-')) return true;
  return FIRST_PARTY_SUFFIX_PREFIXES.some((prefix) => suffix.startsWith(prefix));
}

/** True when a canonical or adapter Skill path belongs to a first-party AICG Skill family. */
export function isFirstPartyGeneratedSkill(relative) {
  if (typeof relative !== 'string') return false;
  if (relative.startsWith('docs/ai/skills/')) return isFirstPartySuffix(relative.slice('docs/ai/skills/'.length));
  for (const directory of declaredSkillDirectories()) {
    if (relative.startsWith(directory + '/')) return isFirstPartySuffix(relative.slice(directory.length + 1));
  }
  return false;
}

/** Canonical retired Skill paths. */
export function retiredCanonicalSkillPaths() {
  return RETIRED_PROCESS_SKILL_IDS.map((id) => 'docs/ai/skills/' + id + '/SKILL.md');
}
