/**
 * The project delivery workflow is one human-readable document, not a family of phase Skills.
 *
 * The owner's process is fixed: requirement analysis, optional page design, architect PK and
 * plan, task decomposition and development, testing, and repair. Every stage stays in this one
 * file so an agent can read the whole path once instead of loading a Skill per phase. Runtime
 * progress lives in the machine state under `.ai-governance/state/`; the document never stores it.
 */
export const WORKFLOW_DOC = 'docs/WORKFLOW.md';
export const WORKFLOW_KIND = 'project-workflow';

const NL = String.fromCharCode(10);

function zh() {
  return [
    '# 项目交付治理工作流',
    '',
    '> 本文件是本项目唯一的交付流程文档。需求从分析到收敛只走这一条路径，流程不再拆分到多个 Skill。',
    '',
    '## 角色模型',
    '',
    '- 所有角色按需求内容动态组织与添加，不预先固定团队。',
    '- 基础角色：PM、BA、架构师、前端、后端、全栈、设计、测试。',
    '- 专业性强的需求（例如合同、法律、财务、安全）必须引入对应专业人员（例如律师），与 BA 一起分析需求；业务问题由专业人员给出建议。',
    '- 角色参与不构成专业结论或签署；对外受监管的最终结论仍需具备资质的真人确认。',
    '',
    '## 流程',
    '',
    '### 1. 需求分析',
    '',
    '按需求内容组织或添加角色到团队，然后分两种情况：',
    '',
    '- **一句话需求**：根据需求内容分析出完整需求，产出详细需求文档。',
    '- **完整需求**：分析需求内容并逐项检查需求细节。',
    '',
    '两种情况下，发现问题随时提问并让用户确认；未确认的问题保留在需求文档的 `openQuestions`。',
    '',
    '### 2. 页面设计（可选）',
    '',
    '- 需求不涉及前端页面：跳过本步骤。',
    '- 需要前端页面设计：询问用户选择「默认」还是「给出三版设计」。',
    '  - 默认：按项目现有设计系统直接设计，不产出 HTML 稿。',
    '  - 三版设计：产出 3 版展示大概样式的预览稿，供用户选择；选中版本写入流程状态。',
    '- 预览稿只是提案，不进入生产构建。',
    '',
    '### 3. 架构师 PK 与开发 plan',
    '',
    'PM 分配架构师等角色互相 PK：结合实际代码与当前需求、设计，检查是否存在遗漏问题、不确定项和未闭环逻辑。',
    '',
    '- 整理出问题清单，连同根据 PK 结果给出的推荐答案一起询问用户。',
    '- 保证需求与设计最终处于可实施状态，并产出开发 plan。',
    '- plan 摘要绑定进 `planHash`；plan 变更使旧批准失效。',
    '',
    '### 4. 任务拆分与开发',
    '',
    'PM 根据开发 plan 拆分任务并按规模组织团队分配：',
    '',
    '- 颗粒度不要过细；每个团队都要完成完整功能。',
    '- 允许团队之间有依赖关系并据此安排先后开发。',
    '- 不得把一个很大的需求直接分给一个团队。',
    '- 完成后进入测试；行为变更同步所属记忆页。',
    '',
    '### 5. 测试',
    '',
    'PM 分配专业测试或真实用户进行功能测试，给出最终测试报告。',
    '',
    '- 自动化、AI 模拟真人与真实用户的结果必须分开记录。',
    '- 未执行的用例记 `NOT_RUN`，未通过的记 `FAIL`；不得把未跑过的用例写成通过。',
    '',
    '### 6. 修复',
    '',
    '- 不需要用户确认的**非业务问题**：自动安排团队修复并重测。',
    '- **业务问题**：置为等待负责人确认，确认后再修复；不得自行拍板。',
    '',
    '## 任务分级',
    '',
    '等级由 `aicg route` 依据改动、范围、风险和清晰度给出，不靠人工感觉：',
    '',
    '- `L0` 只读解释、评审、状态：不建立流程状态。',
    '- `L1` 本地低风险或非生产改动：定位、修改、定向验证。',
    '- `L2` 产品行为、业务契约或多模块：需求与 plan 获批后实施、验证。',
    '- `L3` 多面、架构、迁移、外部动作或高后果：需求、设计、plan 全部获批后集成实施与验证。',
    '',
    '## 状态与证据',
    '',
    '- 项目流程状态：`.ai-governance/state/flow-state.json`；交付循环状态：`.ai-governance/state/delivery-loop.json`。工具只写空基线，之后由执行方维护。',
    '- 分级与门禁：`.ai-governance/state/task-routing-policy.json` 与 `aicg route`。',
    '- 账本记录的是声明与证据引用，不等于执行或认证。',
    '',
    '## 完成定义',
    '',
    '- 需求、设计与 plan 的未决问题都已获得用户确认。',
    '- 开发完成并运行任务所需的仓库验证命令，保存测试结果报告。',
    '- 行为变更同步所属记忆页；未确认的内容保持 `unverified` 或 gap。',
    '- 交付前运行一次 `aicg complete`。',
    '',
  ].join(NL);
}

function en() {
  return [
    '# Project Delivery Workflow',
    '',
    '> This is the only delivery workflow document in this repository. A requirement moves from analysis to convergence along this single path; the process is never split across phase Skills.',
    '',
    '## Role model',
    '',
    '- Every role is organised and added from the requirement content; no team is fixed in advance.',
    '- Base roles: PM, BA, architect, frontend, backend, full-stack, design, test.',
    '- A specialised requirement (contracts, legal, finance, security) must add the matching specialist (for example a lawyer) to analyse the requirement with the BA; the specialist advises on business questions.',
    '- Role participation is not a professional conclusion or a signature; a regulated outward conclusion still needs a qualified human.',
    '',
    '## Flow',
    '',
    '### 1. Requirement analysis',
    '',
    'Organise or add roles to the team from the requirement content, then branch:',
    '',
    '- **One-line requirement**: analyse it into a complete requirement and produce a detailed requirement document.',
    '- **Complete requirement**: analyse the content and check the requirement details item by item.',
    '',
    'In both branches, ask the user whenever a question appears and get confirmation; unresolved points stay in the requirement document `openQuestions`.',
    '',
    '### 2. Page design (optional)',
    '',
    '- The requirement has no frontend page: skip this step.',
    '- It needs frontend design: ask the user to choose default or three designs.',
    '  - Default: design directly from the existing design system; no HTML draft.',
    '  - Three designs: produce three rough-style preview drafts for the user to choose; record the chosen one in the flow state.',
    '- A preview draft is a proposal and never enters the production build.',
    '',
    '### 3. Architect PK and development plan',
    '',
    'The PM assigns architects and peer roles to run a PK against the actual code and the current requirement and design, checking for omissions, uncertainties and unclosed logic.',
    '',
    '- Collect the questions and ask the user together with the recommended answers from the PK result.',
    '- Ensure the requirement and design are implementable, and produce the development plan.',
    '- Bind the plan summary into `planHash`; a plan change invalidates a prior approval.',
    '',
    '### 4. Task decomposition and development',
    '',
    'The PM decomposes the plan and organises teams by task size:',
    '',
    '- Keep granularity coarse; each team must deliver a complete capability.',
    '- Teams may depend on each other and be sequenced accordingly.',
    '- Never hand one very large requirement to a single team.',
    '- After development, move to testing; synchronise the owning memory page for behaviour changes.',
    '',
    '### 5. Testing',
    '',
    'The PM assigns professional testers or real users to run functional testing and produces the final test report.',
    '',
    '- Record automated, AI-simulated-human and real-user results separately.',
    '- Record unrun cases as `NOT_RUN` and failures as `FAIL`; never report an unrun case as passing.',
    '',
    '### 6. Repair',
    '',
    '- **Non-business issues** that need no user confirmation: assign a team automatically, fix and retest.',
    '- **Business issues**: wait for owner confirmation before repairing; never decide unilaterally.',
    '',
    '## Task levels',
    '',
    'The level comes from `aicg route` based on mutation, scope, risk and clarity, not intuition:',
    '',
    '- `L0` read-only explanation, review or status: no flow state.',
    '- `L1` low-risk local or non-production change: locate, edit, targeted verification.',
    '- `L2` product behaviour, business contract or multi-module: implement and verify after requirement and plan approval.',
    '- `L3` multi-surface, architecture, migration, external action or high consequence: implement and verify after requirement, design and plan approval.',
    '',
    '## State and evidence',
    '',
    '- Project flow state: `.ai-governance/state/flow-state.json`; delivery loop state: `.ai-governance/state/delivery-loop.json`. The tool writes only the empty baseline; the executing side owns it afterwards.',
    '- Levels and gates: `.ai-governance/state/task-routing-policy.json` and `aicg route`.',
    '- A ledger records declarations and evidence references, not execution or certification.',
    '',
    '## Definition of done',
    '',
    '- Every open requirement, design and plan question has owner confirmation.',
    '- Development is complete, the repository verification commands the task needs were run, and a test report is saved.',
    '- Behaviour changes synchronised the owning memory page; unconfirmed content stays `unverified` or a gap.',
    '- Run `aicg complete` once before delivery.',
    '',
  ].join(NL);
}

export function workflowDocument(config) {
  return config?.artifactLanguage === 'zh-CN' ? zh() : en();
}

export function buildWorkflowArtifacts(config) {
  return {
    artifacts: [{
      path: WORKFLOW_DOC,
      content: workflowDocument(config),
      ownership: 'full',
      kind: WORKFLOW_KIND,
      source: 'template:project-workflow',
    }],
  };
}
